### ISSUE TITLE
Release for sbt 1.x

### ISSUE THREAD

**Issue by raboof** [ThoughtWorksInc/sbt-best-practice#3]
Looked into this for a bit, but the workaround for https://github.com/sbt/sbt/issues/2514 in this project makes it tricky. Will leave it for now.

**Comment by Atry** [comment]
Yes, it's tricky because it's a workaround, unfortunately...

**Comment by Atry** [comment]
Done in https://github.com/ThoughtWorksInc/sbt-best-practice/commit/6138e2f3cb77869c4e61125d5412107a803ca45f
